# Docker Compose for Backend API Only
# Frontend has been moved to a separate location

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medication-backend
    ports:
      - "5000:5000"
    environment:
      # Database
      - MONGODB_URI=${MONGODB_URI}
      
      # Session
      - SESSION_SECRET=${SESSION_SECRET:-your-secret-key-change-this-in-production}
      
      # Server
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5000
      
      # CORS (set to your frontend URL in production)
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:3000}
      
      # Cloudinary
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      
      # Email Service
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@medication.com}
      
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --quiet --tries=1 --spider http://localhost:5000/api/auth/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
